version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}

        - run: 
            name: Installing Dependencies
            command: npm install 

        - run:
            name: Installing Helix CLI
            command: npm install @adobe/helix-cli

        - run:
            name: Checking CLI Version
            command: ./node_modules/.bin/hlx --version

        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - run:
            name: Building Templates
            command: ./node_modules/.bin/hlx build


        - run:
            name: Deploying to Adobe I/O Runtime
            command: ./node_modules/.bin/hlx deploy --no-auto --wsk-auth $WSK_AUTH --loggly-auth $LOGGLY_AUTH --wsk-namespace trieloff --loggly-host trieloff